/**
 * Cloudflare R2 Upload Service
 * 
 * Uses pre-signed URLs generated by the Vercel API endpoint
 * This is more secure than exposing credentials to the frontend
 */

export const uploadImageToR2 = async (
  file: File,
  fileName: string
): Promise<string> => {
  try {
    // Step 1: Request pre-signed URL from backend
    const uploadUrlResponse = await fetch('/api/upload-url', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        fileName: fileName,
        fileType: file.type,
      }),
    })

    if (!uploadUrlResponse.ok) {
      throw new Error(`Failed to get upload URL: ${uploadUrlResponse.statusText}`)
    }

    const { uploadUrl, publicUrl } = await uploadUrlResponse.json()

    // Step 2: Upload file directly to R2 using pre-signed URL
    const uploadResponse = await fetch(uploadUrl, {
      method: 'PUT',
      body: file,
      headers: {
        'Content-Type': file.type,
      },
    })

    if (!uploadResponse.ok) {
      throw new Error(`Failed to upload file: ${uploadResponse.statusText}`)
    }

    // Step 3: Return the public URL
    return publicUrl
  } catch (error) {
    console.error('Error uploading to R2:', error)
    throw error
  }
}

export default { uploadImageToR2 }
